package com.sentinelai.sentinel.classifier;

public enum FailureType {
    PAYMENT_PROVIDER_TIMEOUT,
    PAYMENT_DECLINED,
    PAYMENT_RETRY_EXHAUSTED,
    INGESTION_FAILED,
    CHECKOUT_FLOW_DEGRADATION,
    ORDER_STATE_ANOMALY,
    STOCK_RESERVATION_TIMEOUT,
    STOCK_CONSISTENCY_RISK,
    UNCLASSIFIED
}
